name: ctm

dependencies:
    - python
    - scipy
    - matplotlib>=2.2.2
    - numpy>=1.14.2
    - cython
    - pip:
      - classylss
      - mcfit
      - nbsphinx
      - sphinx_hand_theme
      - jupyter-sphinx
      - seaborn
