name: ctm-module

dependencies:
    - python
    - scipy
    - matplotlib>=2.2.2
    - numpy>=1.14.2
    - cython
    - pip:
      - classylss
      - mcfit
      - nbsphinx
      - jupyter-sphinx
      - seaborn
      - sphinx-rtd-theme
